ARG version
FROM almalinux:${version:-8}
ARG course="Docker"
ARG trainer="siva"
ARG Duration=120hrs
ENV Duration=${Duration}
RUN echo "The course name is ${course} and the trainer name is  ${trainer} "
CMD ["sleep","1000"]
		